### ISSUE TITLE
Validation for hour number between 25 - 29

### ISSUE THREAD

**Issue by lukyth** [radumardale/react-keyboard-time-input#4]
A user is able to type an hour with 25 - 29, which is not a valid hour.
<img width="275" alt="screen shot 2018-11-15 at 6 19 06 pm" src="https://user-images.githubusercontent.com/7040242/48549657-f8e89a80-e902-11e8-8ae0-5e827b9f55f6.png">
We should have a check for that.

**Comment by radumardale** [comment]
Thanks for this!
This repo isn't maintained.
You should check out [alanclarke/time-input](https://github.com/alanclarke/time-input), the project this was forked from.

**Comment by lukyth** [comment]
Thank you for the clarification! 😄
